[profile.dev]
lto = "off"

[profile.release]
strip = "debuginfo"
codegen-units = 1
lto = "fat"

[workspace]
members = [
  "rust/day1/a",
  "rust/day1/b",
  "rust/day2/a",
  "rust/day2/b",
  "rust/shared"
]
